version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: youapp-backend
    restart: always
    ports:
      - 80:8080
    command: bash -c /usr/src/app/start.sh
    env_file: .env